name: CI
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    env:
      NIM_VERSION: '1.2.0'
    steps:
    - uses: actions/checkout@master
    - uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: ${{ env.NIM_VERSION }}
    - name: Install optional dependencies
      run: nimble install nimcr -y
    - name: Build files
      run: nimble release
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: helics
        path: dist/*
    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: 'dist/*'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-linux-arm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build files
        uses: docker://nonylene/nim-crosscompile
        with:
          entrypoint: /bin/nimble
          args: releasearm
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: helics
          path: dist/*
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: 'dist/*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
